Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "forwarded_port", guest: 8080, host: 4040
  config.vm.network "forwarded_port", guest: 443, host: 4041
  config.vm.network "forwarded_port", guest: 9000, host: 4042
  config.vm.network "forwarded_port", guest: 3000, host: 4043
  config.vm.network "private_network", ip: "192.168.56.27"
  config.vm.network "public_network"
   config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
     vb.memory = "4096"
   end
end

# vagrant up ; vagrant ssh
